name: jaredweakly
version: 0.1.0.0
github: 'jared-w/jaredweakly.com'
license: MIT
author: 'Jared Weakly'
maintainer: 'jaredweakly@gmail.com'
copyright: '2019 Jared Weakly'

extra-source-files:
    - README.md

synopsis: My website
category: Website

description: My personal website.

dependencies:
    - base >= 4.7 && < 5
    - shake
    - slick
    - text
    - containers
    - unordered-containers
    - lens
    - aeson
    - lens-aeson
    - hasmin
    - process

executables:
    build:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall

default-extensions:
    - DataKinds
    - DeriveAnyClass
    - DeriveGeneric
    - DuplicateRecordFields
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - OverloadedStrings
    - PolyKinds
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - TemplateHaskell
    - TypeApplications
    - TypeFamilies
    - TypeOperators
    - NamedFieldPuns
