name: jaredweakly
version: 0.1.0.0
synopsis: My website
description: My personal website.
category: Website
author: Jared Weakly
maintainer: jaredweakly@gmail.com
copyright: 2020 Jared Weakly
github: jared-w/jaredweakly.com
extra-source-files: [README.md]

ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall

dependencies:
  - aeson
  - base >=4.7 && <5
  - containers
  - hasmin
  - lens
  - lens-aeson
  - pandoc
  # - pandoc-emphasize-code
  - pandoc-types
  - process
  - shake
  - slick
  - text
  - time
  - unordered-containers

executables:
  build:
    main: Main.hs
    source-dirs: app
    other-modules:
      - Pandoc

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - OverloadedStrings
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - NamedFieldPuns
